return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "gopls",
        "json-lsp",
        "prettier",
        "eslint-lsp",
        "lua-language-server",
        "typescript-language-server",
        "vue-language-server",
        "pyright",
        "goimports",
        "gofumpt",
        "tailwindcss-language-server",
        "markdown-toc",
        "markdownlint",
        "markdownlint-cli2",
        "marksman",
        "docker-compose-language-service",
        "yaml-language-server",
        "ruff",
        "ruff-lsp",
      },
    },
  },
}
